services:
  ddclient:
    container_name: ddclient
    image: lscr.io/linuxserver/ddclient:latest
    restart: unless-stopped
    volumes:
      - ./ddclient.conf:/config/ddclient.conf
    environment:
      - PUID: 1000
      - PGID: 1000
      - TZ: "Etc/UTC"
      - CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
